travis:
  secure:
    BINSTAR_TOKEN: VJ0k52kSL2wOTasSixZaGifnlJe71zCGNtEfBVeZjCr+Q7PqB9rrHVtsk5/eZ2nSQqfUvM43WO7isHE5gwNER7zVRIQ+VzbjXQv/1751hfbRZOfwuArWNP5YV4/PFQIYclNTld/pok3OjAw//ZDWuTJSKR1VBTLqNsBJtsN/W4dgA6NrImjkxWDgDdnZ5qXlqngR87LZAqBoMdjJQjSwBTvsq8hRUGsX1T5WhwlcyBqgXQPGe2wRxZIBHUlaPn5l8z2xIBHmBcQw4kGXUd5i6p1bUPebWe0eqFOJxoChLB09bhnZZtcZeL9ZrQ9mlSugQoE7DhxdfxMryQSwnX1BT7doMVNcKqIuareVAxSQoy1+MI99sPldoECaa34JCjkOuBE6dCGBvW3h6NmmQvgxBVlMj48+/bxGILyzOw4ocxg96371FJIW6j+7lFdpiOpycRd38A//dyx1Qai+5vk+P1XRidj9QwIYjtam5884e72vD7Rz+k1p7Bp0LcbXPvZJY/ke8IcXtEzPOCXgUWcEfBpsvewFecqszarz4BPXFkQPXew0lWCDBAXA2De+idL89fKVsAwocDTr5UWWPoAW4sx9XbN1bWTLtvtsVkufsgY7qbB6aVjDCgq1ghp+WlJ9IbKw2JtZL2Ia8IyBdh2mZqLPuSyD0gDfBZ97/uW+HA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
