appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: r+fPbQ15OvRQ1I5JoN+UxeXLlCsswB0j+KkYFSsOeBTVU5c00TjL2RczBCcn0aExNkIWlkc1xeXdUgMLFffl5vrvs5DJuzDl11oDUWJB/kMSoVV0X+ihwlimPzLWrK9JB1eKrZETOcUBeaLg1Qj8YIpVP4OTB5FXUIFWjdlGc+47855xDueCPhN4JVrqK1GWaWNw2yFzDjqkIhQMlHnsUGqhf4GtsoEQLxlWkw/D70qnpIPMJGsVBf+R+NZY6SKtAKfPczC4tAPqXKmVLvig+3BcmdQ2L2Q+Ax2Q3UThwJHY9Jz03pP3kI59Gi9WfHr9n2IMB3OFSKGasBPqPZy36QzrxkbikvgTYru5VRY8pgjNsGOkMI4mJ5yGEk1PENYUPbT/uQ7/yE3iR3VuMer2s47rGwi3H424giROdBQqWILUiYzeuwhFyHQbfeHTUJDIxLJOb2JEehABjoNIVsrmvd5yLfr8t8cljT7UTdSy4FnwxwTtqFWV0l/9Iwl0t96dh94WI0PyV0Z5Bp6FmY/+g9RxmZCvI89CqQoQbsIn6Lycrky0EtQqvvBW6J+qSrKqErecOa8Y2SC8OIaCGy2r4pjWt9HvCFKFT4ZXwDHEd/SlJgZeCAcxF40XrbSW6ur3i0o1xLr7a6mC0li/oDrJynPW0NJCrkMIfiF18g88JU0=
